spring.application.name=yarnstash
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/yarnstash}
spring.datasource.username=${DB_USERNAME:yarnstash}
spring.datasource.password=${DB_PASSWORD:yarnstash}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true